### ISSUE TITLE
compat: vim.Function

### ISSUE THREAD

**Issue by blueyed** [neovim/pynvim#411] opened 2019-09-17 16:47 UTC
I think it would good to support `vim.Function()`, basically (hopefully) mapping it to `vim.funcs`.

Without this plugins need to use different codepaths for Vim and Neovim.

Vim doc: https://github.com/blueyed/vim/blob/bd20b92d027baad3f9b86d5c8bee30de55cd932a/runtime/doc/if_pyth.txt#L676-L724

**Comment by justinmk** [comment] 2019-09-18 04:23
quite a lot of work for a pretty low-priority item.

duplicate of https://github.com/neovim/neovim/issues/1898

**Closed by justinmk** 2019-09-18 04:23 UTC
Labels: enhancement

**Comment by bfredl** [comment] 2019-09-18 10:41
Perhaps we could implement only the case with no args and no self, like ` vim.Function('getcurpos')`. I think many plugins use this to call builtin functions at all (instead of `vim.eval` string hacking), and don't care about the args/self case (which would require references/bindeval).

**Comment by blueyed** [comment] 2019-09-18 13:14
Yes, `vim.Function('getcurpos')` would be enough for my use case already.

Without looking into details I've assumed that using self/args kwargs could also be done using a partial rather easily, but that appears to not be the case then?!

**Comment by bfredl** [comment] 2019-09-18 13:27
> Without looking into details I've assumed that using self/args kwargs could also be done using a partial rather easily, but that appears to not be the case then?!

I assume it creates a vim partial, with direct references to vim dictionaries/lists, otherwise it wouldn't be much point of having this functionality.
