### ISSUE TITLE
add a timeout argument to `attach()` (and underlying objects)

### ISSUE THREAD

**Issue by amigrave** [neovim/pynvim#231] opened 2016-10-23 15:02 UTC
I still didn't understood why, but sometimes I've got some neovim instances file sockets not responding when trying to send a signal through the neovim client.

I guess one wants to set a timeout in case things goes wrong.

**Comment by amigrave** [comment] 2016-12-06 16:48
Just got the problem due to an unresponsive neovim socket:

```
DEBUG:neovim.msgpack_rpc.msgpack_stream:sent [0, 2, 'vim_eval', ('getcwd()',)]
DEBUG:neovim.msgpack_rpc.event_loop.base:Sending '<94>^@^B<A8>vim_eval<91><A8>getcwd()'
DEBUG:neovim.msgpack_rpc.event_loop.base:Entering event loop
```
Then it just blocks...

I integrated neovim in terminator (as a python plugin) hence I've got my terminal completely frozen when that happens.
A way to specify a timeout would be handy.

**Comment by justinmk** [comment] 2018-11-18 23:36
The root cause of this problem should be addressed by this change to Nvim core: https://github.com/neovim/neovim/pull/9024

Timeouts are also a good idea, but that would most likely be addressed by a more generic change to Nvim core API.

**Closed by justinmk** 2018-11-18 23:36 UTC
Labels: enhancement
